/*FAÇA UM PROGRAMA QUE PEDE PARA O USUÁRIO DIGITAR 4 NOTAS E GUARDA ESSAS NOTAS EM UM ARRAY

DEPOIS PERCORRA ESSE ARRAY E FAÇA A SOMA TOTAL DE TODAS AS NOTAS

DEPOIS CALCULE A MÉDIA DAS NOTAS

DEPOIS CHEQUE SE O ALUNO FOI APROVADO OU REPROVADO (MÉDIA 7)*/

for(let i = 1; i <=4; i++){
    const nota = Number(prompt("Digite uma nota"))
    alert({nota});
}