/*FAÇA UM PROGRAMA QUE PEDE PARA O USUÁRIO DIGITAR 4 NOTAS E GUARDA ESSAS NOTAS EM UM ARRAY

DEPOIS PERCORRA ESSE ARRAY E FAÇA A SOMA TOTAL DE TODAS AS NOTAS

DEPOIS CALCULE A MÉDIA DAS NOTAS

DEPOIS CHEQUE SE O ALUNO FOI APROVADO OU REPROVADO (MÉDIA 7)*/

const nota = parseFloat(prompt("Digite a nota"))
