FAÇA UM PROGRAMA QUE PEDE PARA O USUÁRIO DIGITAR UMA QUANTIDADE ILIMITADA DE PRODUTOS, ONDE PARA CADA PRODUTO ELE DIGITARÁ: nome, preço E GUARDARÁ EM UMA LISTA, E ESSA LISTA GUARDARÁ EM UMA LISTA MAIOR CHAMADA estoque, QUANDO O USUÁRIO RESOLVER ENCERRAR VOCÊ VAI:
MOSTRA QUAL FOI O PRODUTO MAIS CARO VENDIDO
MOSTRA QUAL FOI O PRODUTO MAIS BARATO VENDIDO
MOSTRA O TOTAL QUE FOI VENDIDO (QUANTOS ITENS E QUAL VALOR DA SOMATÓRIA DELES)